.travis.yml

This PR adds a very simple `.travis.yml` configuration which

Enhancement: Use Travis for running a few things here and there

---

.gitignore

Fix: Ignore directory into which coverage is generated

---

Makefile

This PR
Run 
```
$ make test
```

Enhancement: Add Makefile with test target

---

README.md

The "Closure Based" routing example is missing a parenthesis and the function name is capitalized.

Fix Closure Based example

---

README.md

Fix: A few issues with README.md

---

composer.lock

Fix: The lock file is not up to date

---

src/Hooks/Hookable.php

Fix: Inconsistent docblock

---

spec/Router/PistonStrategySpec.php

Fix: Remove redundant assertion

---

composer.json
composer.lock

This PR
Follows https://github.com/refinery29/piston/commit/fb5855408f7e762c0e4001d857711d04c3d7cc09.
Related to https://github.com/refinery29/piston/pull/31#discussion_r33891529.

Enhancement: Require PHP 5.5 or greater

---

src/Router/PistonStrategy.php

Fix: Remove else as we're returning already

---

src/Router/Routes/RouteGroup.php

Fix: Let use statement be first statement in class

---

src/Router/Routes/RouteGroup.php

Fix: Docblock for instance property and return value

---

src/Router/Routes/Route.php

Fix: Type should probably be string

---

src/Hooks/Fields.php
src/Hooks/IncludedResource.php
src/Hooks/Pagination.php

Fix: No need for double parentheses

---

src/Router/RouteCollection.php

This PR
Follows https://github.com/refinery29/piston/pull/29#issuecomment-118858675.

Fix: Remove unused property

---

Makefile

This PR
:information_desk_person: This is helpful for the extra-lazy among us, who start coding by pulling from `master` and running the tests first with 
```
$ make test
```

Enhancement: Add composer target to Makefile

---

.editorconfig

Fix: Add .editorconfig configuration for Makefile

---

composer.json
composer.lock

This PR
See https://travis-ci.org/refinery29/piston/jobs/74159157#L221:
> /home/travis/build.sh: line 41: vendor/bin/test-reporter: No such file or directory

Fix: Require codeclimate/php-test-reporter as a development dependency

---

.travis.yml

This PR
:information_desk_person: Code Climate says that only the first payload will be accepted, so it makes sense to fix it to one build.

Fix: Only collect coverage on PHP5.6

---

spec/Hooks/Pagination/CursorBasedPaginationSpec.php
spec/Hooks/Pagination/OffsetLimitPaginationSpec.php
spec/Http/JsonResponseSpec.php
spec/Http/ResponseNegotiatorSpec.php
spec/PistonSpec.php
spec/Router/PistonStrategySpec.php
spec/stubs/FooBarResponse.php
src/Http/ResponseNegotiator.php
src/Piston.php
src/Router/HookProcessor.php

After discussion with Travis, this PR:

Refactor some Response stuff

---

spec/Pipeline/Stage/Pagination/OffsetLimitPaginationSpec.php
src/Http/Request.php

Fix: Do not declare fields dynamically

---

src/Http/Request.php

Fix: Do not use is_null(), compare against null instead

---

src/Http/Request.php

Fix: Docblocks which indicate that fields are of type 'var'

---

.gitignore

Fix: Ignore the bin dir

---

composer.json
composer.lock

Fix: Keep items in composer.json in order

---

.gitignore
.travis.yml
bin/report-coverage
composer.json
composer.lock

Fix: Require codeclimate/php-test-reporter:0.2.0

---

.travis.yml

Fix: Run build on PHP5.6

---

spec/Http/ResponseSpec.php
src/Http/Response.php
src/Http/ResponseInterface.php

A default `ResponseBody` object is not instantiated if the `Response` is constructed with a null `ResponseBody`.
```php
use Refinery29\Piston\Http\Response;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;
$response = new Response(new SymfonyResponse());
$response->getContent(); // error
```

[Response] Instantiate ResponseBody when null

---

src/Piston.php

* Route Groups are not added to `Piston#$groups`
* `@return` type is more accurate as `Refinery29/Piston/Route/RouteGroup`

Fix: Adding Route Groups

---

src/Response.php

`Zend\Diactoros\Response#getBody` returns a `StreamInterface`

Correct Response#compileContent return type annotation

---

spec/Middleware/Request/IncludedResourceSpec.php
src/Middleware/Request/IncludedResource.php

`IncludedResource#ensureGetOnlyRequest()` was called when the `include` query parameter was not present.
Thus, any non-GET requests encountered a thrown `League\Route\Http\Exception\BadRequestException`.
The Request should only be ensured that it is a GET request when the `include` query parameter is present.

Only ensure GET request when include query present

---

spec/ResponseSpec.php
src/Response.php

`Response#withHeader` returns a new/cloned `Response` object and should not be used in a constructor.

Add Response Content-Type header with Constructor

---

spec/ApiResponseSpec.php
spec/Middleware/PayloadSpec.php
spec/Middleware/PipelineProcessorSpec.php
spec/Middleware/Request/IncludedResourceSpec.php
spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/Middleware/Request/RequestPipelineSpec.php
spec/Middleware/Request/RequestedFieldsSpec.php
spec/PistonSpec.php
spec/ResponseSpec.php
spec/Router/MiddlewareStrategySpec.php
spec/stubs/FooController.php
src/ApiResponse.php
src/CompiledResponse.php
src/Middleware/Payload.php
src/Piston.php
src/Router/MiddlewareStrategy.php

This PR: 
Currently Piston only allows for a `Piston\Response` to be used and returned. Anything else will result in an error. This PR makes it so that only compiled responses are compiled and any other response is allowed to continue on as normal. This will allow for `HTMLResponse` to be used, or even an XMLResponse or any custom Response object

Allow for Other response

---

README.md
spec/Middleware/Request/SortsSpec.php
src/Middleware/Request/RequestPipeline.php
src/Middleware/Request/Sorts.php
src/Request.php

* New `Sorts` Request stage
* Parse `sort` query parameter into an associative array of `[columnToSort => 'ASC'|'DESC]`
* Adheres to Sort API Standard https://github.com/refinery29/api-standards#sorting

Sort Request Stage

---

CONTRIBUTING.md
Makefile

This PR
:information_desk_person: Run
```
$ make
```

Fix: Add it target

---

src/Piston.php

This change became required after completing `cbc843g` in https://github.com/refinery29/piston/pull/121cbc843f. That work changes Piston to work in an immutable manner, as the underling ServerRequest does.
The reason why is that the original objects are changed during processing pipelines. But when working immutably, if changes are made during the pipeline, the original object is replaced with a _new_ object, which contains all of the state of the original, as well as the required changes.
Therefore, any changes made will be lost as, for all intents and purposes, without this change, we're making changes to a copy of the request and response. So after the processing is complete, the changes will be lost. Given that, we have to be more pedantic in how the object is used throughout the …

Update Piston's Request and Response objects after Middleware Pipelines Finish Processing

---

phpspec.with-coverage.yml.dist

This PR
Follows #123.
:information_desk_person: This allows to run specifications without xdebug installed.

Fix: Create specific configuration without coverage generation

---

phpspec.with-coverage.yml.dist

Fix: Output text coverage

---

CONTRIBUTING.md
Makefile

This PR
:information_desk_person: Run
```
$ make coverage
```

Fix: Add coverage target

---

spec/ApiResponseSpec.php
spec/CookieJarSpec.php
spec/Middleware/PayloadSpec.php
spec/Middleware/PipelineProcessorSpec.php
spec/Middleware/Request/IncludedResourceSpec.php
spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/Middleware/Request/RequestPipelineSpec.php
spec/Middleware/Request/RequestedFieldsSpec.php
spec/Middleware/Request/SortsSpec.php
spec/PistonSpec.php
spec/RequestSpec.php
spec/Router/MiddlewareStrategySpec.php
spec/Router/RouteGroupSpec.php
spec/Router/RouteSpec.php

This PR
:information_desk_person: This greatly improves developer convenience as now it is possible to navigate to the methods invoked on the system under test.

Fix: Mix in system under test

---

composer.json
composer.lock
spec/ApiResponseSpec.php

This PR
For reference, see https://github.com/zendframework/zend-diactoros/compare/1.1.3...1.3.3.

Fix: Update zendframework/zend-diactoros

---

src/Middleware/HasMiddlewareTrait.php
src/Piston.php
src/Request.php

This PR
:information_desk_person: It's the default.

Fix: No need to assign null as default value

---

phpspec.with-coverage.yml
phpspec.yml

This PR
Follows https://github.com/refinery29/piston/pull/137.

Fix: Consistently indent yml with 2 spaces

---

composer.json
composer.lock
spec/PistonSpec.php
spec/Router/MiddlewareStrategySpec.php
spec/Stubs/FooController.php
spec/Stubs/ReturnEmitter.php
spec/Stubs/StringEmitter.php
spec/Stubs/TestException.php

Fix: Move stubs into appropriate namespace

---

spec/PistonSpec.php
spec/Router/MiddlewareStrategySpec.php
spec/Stub/FooController.php
spec/Stub/ReturnEmitter.php
spec/Stub/StringEmitter.php
spec/Stub/TestException.php

Fix: Use singular for namespace

---

.phpspec/specification.tpl

Fix: Mix in the subject into the specification

---

src/Request.php

Fix: Move constructor into right location

---

spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/PistonSpec.php
spec/Router/MiddlewareStrategySpec.php

This PR
:information_desk_person: This is part of a series, intending to clean up the specifications.

Fix: Use class keyword

---

src/Middleware/ExceptionalPipeline.php

Fix: Use Assertion

---

spec/Stub/ReturnEmitter.php
spec/Stub/StringEmitter.php

Fix: Return types in docblocks

---

spec/PistonSpec.php
spec/Stub/PassThroughEmitter.php

This PR
Follows #149.
:information_desk_person: All emitters return something - this one, though, passes through the response object passed to it.

Fix: Rename ReturnEmitter to PassThroughEmitter

---

src/Piston.php

Fix: Rename setupDefaultExceptions() to registerNotFoundExceptionHandler()

---

README.md

This PR
:information_desk_person: Neither of these are best practice.

Fix: Suggest to install via composer only

---

composer.json
composer.lock

This PR
:information_desk_person: It's generally bad practice to use a floating constraint for unstable dependencies, see http://semver.org/#spec-item-4:
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Fix: Pin unstable dependencies

---

Makefile
composer.json
composer.lock
test/Unit/phpunit.xml

This PR
Replaces https://github.com/refinery29/piston/pull/155.

Enhancement: Use phpunit/phpunit for unit testing

---

.editorconfig

Fix: Allow to indent json files with 2 spaces

---

src/Middleware/HasMiddlewareTrait.php

Fix: No need to assign and then immediately re-assign

---

test/Unit/Middleware/ExceptionalPipelineTest.php

Fix: Add direct coverage for ExceptionalPipeline

---

test/Unit/Middleware/ExceptionalPipelineTest.php

This PR
Follows #164.
Blocks #165.

Fix: Assert stages are set on new instance

---

.travis.yml
Makefile

This PR
Follows #161.
:information_desk_person: The coverage generated from running specifications is in fact misleading, as a lot of code is only indirectly tested as part of integration tests. Coverage should only be generated from unit tests, though.

Fix: Do not generate coverage when running specifications

---

.gitignore

Fix: Remove irrelevant entry from .gitignore

---

src/CookieJar.php
test/Unit/CookieJarTest.php

Fix: Allow to clear cookie when the value for the key is null

---

src/CookieJar.php
test/Unit/CookieJarTest.php

Fix: Assert that cookie can be cleared even if key does not exist

---

src/CookieJar.php

Fix: Do not use isset

---

src/CookieJar.php
test/Unit/CookieJarTest.php

Fix: Reject invalid keys when working with CookieJar

---

.travis.yml
composer.json
composer.lock

Fix: Drop support for PHP 5.5

---

test/Unit/CookieJarTest.php
test/Unit/Middleware/ExceptionalPipelineTest.php

Fix: Do not use deprecated setExpectedException()

---

src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Request.php

This PR
This isn't a big thing, but worthwhile for sakes of consistency.

Enhancement: Rename all variables and function arguments to be camel-cased

---

composer.json
composer.lock

This PR
Follows https://github.com/thephpleague/route/tree/2.0.0

Fix: Require league/route:^2.0.0

---

src/Request.php
test/Unit/RequestTest.php

In order to support proper error reporting, we need access to the list of sorts that are provided.
This will allow us to maintain the order of multiple sorts as well

Add in a getSorts method

---

src/Request.php
test/Unit/RequestTest.php

Bug: make requested fields array by default

---

spec/Middleware/Request/IncludedResourceSpec.php
src/Middleware/Request/IncludedResource.php

This PR
❓ The `includes` query paramter is used during transformation/serialization and can be used when performing UPDATE (`PUT`, `PATCH`, `POST)` methods to ensure certain resources are included in the response.

Allows includes query parameter on non-get requests

---

composer.json
composer.lock
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Request.php
test/Unit/RequestTest.php

This PR
💁 For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.4.15...0.4.18.

Fix: Update refinery29/php-cs-fixer-config

---

spec/PistonSpec.php
src/Piston.php

This PR
Follows https://github.com/refinery29/piston/pull/214

Inject Exception into Registered Exception Callable

---

Makefile

This PR
💁‍♂️ For reference, see https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html:
>### 4.6 Phony Targets
>
>A phony target is one that is not really the name of a file; rather it is just a name for a recipe to be executed when you make an explicit request. There are two reasons to use a phony target: to avoid a conflict with a file of the same name, and to improve performance.

Fix: Specify phony targets in Makefile

---

Makefile

Fix: Keep composer updated and validate composer.json

---

.travis.yml

Fix: Add PHP 7.0 to Travis build matrix

---

.travis.yml

Fix: Add PHP 7.1 to Travis build matrix

---

.php_cs
composer.json
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/Middleware/Request/Pagination/PagedPaginationSpec.php
spec/Middleware/Request/SortsSpec.php
src/ApiResponse.php
src/CookieJar.php
src/Middleware/Request/IncludedResource.php
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Middleware/Request/Pagination/PagedPagination.php
src/Middleware/Request/RequestPipeline.php
src/Middleware/Request/RequestedFields.php
src/Middleware/Request/Sorts.php
src/Piston.php
src/Request.php
src/Router/MiddlewareStrategy.php
test/Unit/CookieJarTest.php
test/Unit/RequestTest.php

This PR
💁‍♂️ For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.4.18...0.10.1.

Enhancement: Update refinery29/php-cs-fixer-config

---

composer.json

This PR
Follows #229.
💁‍♂️ We needed this previously only to pull in an unstable version of `friendsofphp/php-cs-fixer`.

Fix: Raise minimum stability to default levels

---

composer.json
test/Unit/CookieJarTest.php
test/Unit/RequestTest.php

This PR
💁‍♂️ For reference, see https://github.com/refinery29/test-util/compare/0.3.0...0.11.4.

Enhancement: Update refinery29/test-util

---

.travis.yml
Makefile
composer.json

Fix: Use default location for binaries installed with composer

---

test/Unit/phpunit.xml

This PR
💁‍♂️ This way it will always be relevant, regardless of the currently installed version of `phpunit/phpunit`.

Fix: Specify path to phpunit.xsd relative to phpunit.xml

---

spec/Stub/FooController.php

Fix: Add missing parameter to method signature
