refinery29/piston

README.md

This PR
Somewhat related to #3.

Enhancement: Add Travis build badge to README.md

---

README.md

Enhancement: Add Code Climate badge to README.md

---

.codeclimate.yml

Enhancement: Use file-based Code Climate configuration

---

composer.json
composer.lock
spec/PistonSpec.php
spec/Router/Routes/RouteGroupSpec.php
spec/Router/Routes/RouteSpec.php
src/Hooks/Hookable.php

Replaced OperationInterface with StageInterface

---

README.md

Enhancement: Leverage syntax highlighting

---

.editorconfig

Adapted from https://github.com/visualchefs/php-standards

Fix #41: Add editorconfig

---

CONTRIBUTING.md

Fix: Update CONTRIBUTING.md

---

spec/Http/RequestTypeNegotiatorSpec.php
src/Http/RequestTypeNegotiator.php

Return JSON Response as default.

Json response default

---

.travis.yml
bin/report-coverage

This PR
See https://github.com/codeclimate/php-test-reporter#known-issue-ssl-certificate-error.

Fix: Attempt to work around Code Climate SSL issue

---

src/Pipeline/HasPipelines.php
src/Pipeline/Stage/GetOnlyStage.php
src/Pipeline/Stage/Pagination/SinglePagination.php

Fix: Add missing docblocks and type-hints

---

spec/PistonSpec.php
spec/Router/PistonStrategySpec.php
src/Piston.php
src/Router/PistonStrategy.php

Fixes #70 
Removes the dispatching of closures, as well as redirect() and 404() functions

remove unnecessary functions.

---

spec/Pipeline/Stage/Pagination/OffsetLimitPaginationSpec.php
src/Http/Pipeline/RequestPipeline.php
src/Http/Request.php

Offset limit update

---

composer.json
composer.lock

Fix: Prefer stable releases

---

README.md
src/Decorator.php
src/Piston.php

CON 576: Update Piston Docs

---

spec/Middleware/PayloadSpec.php
spec/Middleware/PipelineProcessorSpec.php
spec/Middleware/Request/IncludedResourceSpec.php
spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/Middleware/Request/RequestPipelineSpec.php
spec/Middleware/Request/RequestedFieldsSpec.php
spec/PistonSpec.php
spec/RequestSpec.php
spec/ResponseSpec.php
spec/Router/MiddlewareStrategySpec.php
spec/Router/RouteGroupSpec.php
spec/stubs/FooBarResponse.php
spec/stubs/FooController.php
src/Middleware/Payload.php
src/Middleware/PipelineProcessor.php
src/Middleware/Request/Pagination/CursorBasedPagination.php
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Middleware/Request/Pagination/SinglePagination.php
src/Middleware/Request/RequestPipeline.php
src/Middleware/Request/RequestedFields.php
src/Piston.php
src/Request.php
src/Response.php
src/Router/MiddlewareStrategy.php

Increase coverage

---

spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/PistonSpec.php
spec/RequestSpec.php
spec/stubs/FooController.php
spec/stubs/TestEmitter.php
src/Middleware/Request/IncludedResource.php
src/Middleware/Request/Pagination/CursorBasedPagination.php
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Middleware/Request/RequestedFields.php
src/Piston.php
src/Request.php

This PR: 
Fix bugs: 
Adds tests to cover the above fixes.

Additional tests pagination

---

spec/Middleware/PipelineProcessorSpec.php
spec/Middleware/Request/IncludedResourceSpec.php
spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/Middleware/Request/RequestPipelineSpec.php
spec/Middleware/Request/RequestedFieldsSpec.php
src/Piston.php
src/Request.php

Remove request middleware

---

spec/CookieJarSpec.php
spec/Middleware/PipelineProcessorSpec.php
spec/Middleware/Request/IncludedResourceSpec.php
spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/Middleware/Request/RequestPipelineSpec.php
spec/Middleware/Request/RequestedFieldsSpec.php
spec/RequestSpec.php
src/CookieJar.php
src/Piston.php
src/Request.php
src/RequestFactory.php

This PR:
:cookie::cookie::cookie::cookie::cookie::cookie::cookie:

Coooooookie jar

---

spec/Middleware/PipelineProcessorSpec.php
spec/PistonSpec.php
spec/Router/MiddlewareStrategySpec.php
spec/Router/RouteGroupSpec.php
spec/stubs/ReturnEmitter.php
spec/stubs/StringEmitter.php
spec/stubs/TestException.php
src/Middleware/ExceptionalPipeline.php
src/Middleware/HasMiddleware.php
src/Middleware/HasMiddlewareTrait.php
src/Middleware/PipelineProcessor.php
src/Piston.php

This PR: 
- Create ExceptionalPipeline for throwing Exceptions
- Add abilty to register exceptions
- Add default not found exception handling

Introduce exception handling

---

spec/PistonSpec.php

one more test to ensure exception over riding.

---

spec/PistonSpec.php
src/Piston.php

Add error response

---

CONDUCT.md
README.md

Fix: Add missing Code of Conduct

---

composer.json
composer.lock

This PR
:information_desk_person: For reference, see https://github.com/phpspec/phpspec/compare/2.3.0...2.4.1.

Fix: Update phpspec/phpspec

---

src/ApiResponse.php
src/CookieJar.php
src/Middleware/ExceptionalPipeline.php
src/Middleware/GetOnlyStage.php
src/Middleware/HasMiddleware.php
src/Middleware/HasMiddlewareTrait.php
src/Middleware/Request/Pagination/CursorBasedPagination.php
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Middleware/Request/Pagination/SinglePagination.php
src/Middleware/Request/RequestPipeline.php
src/Middleware/Request/RequestedFields.php
src/Piston.php
src/Request.php
src/RequestFactory.php
src/Router/Route.php
src/Router/RouteGroup.php

Fix: Docblocks

---

src/Middleware/HasMiddlewareTrait.php

Fix: Remove unused import

---

spec/stubs/FooController.php

Fix: Remove a useless comment

---

composer.json
composer.lock

This PR
:information_desk_person: Let's use these to generate fake data in specifications.

Enhancement: Require refinery29/test-util and fzaninotto/faker

---

composer.json
composer.lock

Enhancement: Require beberlei/assert

---

spec/CookieJarSpec.php
src/CookieJar.php

Fix: Assertion that array has numeric keys

---

README.md

Fix: Not a function

---

.editorconfig
README.md

Fix: Merge master into 2.0

---

composer.json
composer.lock

Fix: Add branch alias for 2.0

---

composer.json
composer.lock

Fix: Update autoload configuration

---

.travis.yml

This PR
Follows #161.
Blocks #165.

Fix: Actually run unit tests on Travis

---

test/Unit/RequestTest.php

This was discovered as a result of implementing mutation testing in #177.

Add further covering test to withOffsetLimit

---

CONTRIBUTING.md
Makefile
composer.json
composer.lock
humbug.json

This PR
:information_desk_person: I took the freedom to cherry-pick the commits!

Enhancement: Add mutation testing

---

README.md

Fix: Remove broken VersionEye badge

---

.github/PULL_REQUEST_TEMPLATE.md

Fix: Remove extra space from list

---

src/MiddlewareInterface.php

This PR
Replaces #188.
:information_desk_person: In order to easily allow `refinery29/piston` to use existing PSR-7 middleware, as well as to allow users of `refinery29/piston` to switch to a different framework, we should decide to use one of the available choices.
A bunch of projects provide and/or use exactly the same interface, for example
* [`bitexpert/adroit`](https://github.com/bitExpert/adroit)
* [`madewithlove/glue`](https://github.com/madewithlove/glue)
* [`radar/adr`](https://github.com/radarphp/Radar.Adr)
* [`relay/relay`](https://github.com/relayphp/Relay.Relay/blob/1.x/src/MiddlewareInterface.php#L42)
* [`zendframework/zend-expressive`](https://github.com/zendframework/zend-expressive/blob/2db114f9c888e5ce06c808c44c47f70324be4d5c/src/Application.php#L138)
* …

Enhancement: Provide MiddlewareInterface

---

src/Request.php
test/Unit/RequestTest.php

update included resources to be array by default too

---

composer.json
composer.lock

Update Api Output

---

composer.json
composer.lock

Update to API - output 0.3.4

---

composer.json
composer.lock
spec/PistonSpec.php
spec/Router/RouteGroupSpec.php

This PR
💁 For reference, see https://github.com/refinery29/php-cs-fixer-config/compare/0.4.1...0.4.15.

Fix: Update refinery29/php-cs-fixer-config

---

.github/ISSUE_TEMPLATE.md

This PR makes the Issue Template less obnoxious
Over using large headers adds too much to a description.
_Old_
bar
_New_
bar
https://github.com/refinery29/piston/issues/207

Reduce Size of header elements in Issue Template

---

spec/ApiResponseSpec.php

Fix: ApiResponseSpec

---

spec/Middleware/PayloadSpec.php
spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
src/Middleware/Payload.php
src/Middleware/Request/IncludedResource.php
src/Middleware/Request/Pagination/CursorBasedPagination.php
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Middleware/Request/RequestedFields.php
src/Middleware/Request/Sorts.php
src/Request.php
src/Router/MiddlewareStrategy.php

Use with methods to enforce immutability

---

spec/Middleware/Request/Pagination/PagedPaginationSpec.php
src/Middleware/Request/Pagination/PagedPagination.php
src/Middleware/Request/RequestPipeline.php
src/Request.php

POC: PagedPagination

---

composer.json
composer.lock
phpspec.yml

This PR
💁‍♂️ For reference, see https://github.com/phpspec/phpspec/compare/2.3.0...3.3.0.

Enhancement: Update phpspec/phpspec

---

.travis.yml

Fix: Collect coverage also on pull requests

---

src/Middleware/Request/Pagination/CursorBasedPagination.php
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Middleware/Request/Pagination/PagedPagination.php

Fix: Remove unnecessary parentheses

---

.gitignore

Fix: Clean up .gitignore

---

composer.json
spec/Middleware/Request/IncludedResourceSpec.php
spec/Middleware/Request/Pagination/CursorBasedPaginationSpec.php
spec/Middleware/Request/Pagination/OffsetLimitPaginationSpec.php
spec/Middleware/Request/Pagination/PagedPaginationSpec.php
spec/Middleware/Request/RequestPipelineSpec.php
spec/Middleware/Request/RequestedFieldsSpec.php
spec/Middleware/Request/SortsSpec.php
spec/PistonSpec.php
src/Middleware/HasMiddleware.php
src/Middleware/HasMiddlewareTrait.php
src/Middleware/Request/IncludedResource.php
src/Middleware/Request/Pagination/CursorBasedPagination.php
src/Middleware/Request/Pagination/OffsetLimitPagination.php
src/Middleware/Request/Pagination/PagedPagination.php
src/Middleware/Request/RequestPipeline.php
src/Middleware/Request/RequestedFields.php
src/Middleware/Request/Sorts.php
src/Piston.php

https://rpm.newrelic.com/accounts/60268/applications/12511608/traced_errors/b1f4e05b-96ff-11e7-848b-0242ac11000a_831_2807/similar_errors?original_error_id=29074c54-67f4-11e7-a209-0242ac110010_0_2059
stacktrace shows league/pipeline is the issue and a member in that repo fixed the problem, this is a known problem within thephpleague/pipeline github page;
I follow the upgrade instruction from 
https://github.com/thephpleague/pipeline/blob/2a384f086d46e17b4590f9d091cbc1a5d1495880/UPGRADE.md
Only Travis issue is:
```
Problem 1
- humbug/humbug 1.0.0-alpha1 requires phpunit/phpunit ~4.5 -> satisfiable by phpunit/phpunit[4.5.0, 4.5.1, 4.5.x-dev, 4.6.0, 4.6.1, 4.6.10, 4.6.2, 4.6.3, 4.6.4, 4.6.5, 4.6.6, 4.6.7, 4.6.8, 4.6.9, 4.6.x-dev, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, …
```

ZP-1684: Update Pipeline to Fix array_reduce() Bug

---

composer.json

Remove dev names and only include P&E email
